# Generated by Django 4.2 on 2023-07-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_mensage_contatocliente_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatocliente',
            name='tipo',
            field=models.CharField(choices=[('Preciso de um Cuidador', 'Preciso de um cuidador'), ('Sou um Cuidador', 'Sou um cuidador')], default='', max_length=25),
        ),
    ]
