# Generated by Django 4.1 on 2023-09-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
