# Generated by Django 4.1 on 2023-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_post_imagem_remove_post_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
