# Generated by Django 4.1 on 2023-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tituloblog_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem_post',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
